import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Title for first layout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      Layout1
      <div>{children}</div>
    </div>
  );
}
